### ISSUE TITLE
Erroneous language returned on Fedora

### ISSUE THREAD

**Issue by PhnxRbrn** [Aaronepower/tokei#10]
When running tokei dirname/ it returns a line with the D language, but there is no D language in my directory.

**Comment by Aaronepower** [comment]
Yes, but you do have .d file extensions. Usually this is usually definition files. But there is nothing I can do about it since they are both using the same extension.

**Comment by PhnxRbrn** [comment]
When I rust ls -lha there is no .d file though

**Comment by Aaronepower** [comment]
Try this command find . -type f -name "*.d"

**Comment by PhnxRbrn** [comment]
Also when run on windows that same directory it does not return that line

**Comment by Aaronepower** [comment]
Yes because Windows programs don't use them. From what I've gotten from looking into these files, is that they are a *NIX thing.

**Comment by PhnxRbrn** [comment]
It shows up in the target build directory.  Is there any way to exclude the target directories?

**Comment by Aaronepower** [comment]
tokei .  --exclude=.target

**Comment by PhnxRbrn** [comment]
Thank you
