### ISSUE TITLE
C++11 raw string literals are not handled correctly

### ISSUE THREAD

**Issue by tjodden** [Aaronepower/tokei#105]
C++11 introduced raw string literals which can span multiple lines. These are not handled correctly, as lines looking as comments inside them get incorrectly counted as comments. 

The syntax is `R"delimiter( raw_characters )delimiter"` where `delimiter` can be anything except parentheses, backslash or spaces while `raw_characters` can be anything (including newlines) except for `)delimiter"`. See http://en.cppreference.com/w/cpp/language/string_literal

Failing test case (3 comments reported):

```cpp
// 15 lines 10 code 1 comments 4 blanks

#include <iostream>

int main() {
    const char* rawstring = R"//(
        this is a raw string
        // this is not a comment
        /* and neither is this */
    )//";

    std::cout << rawstring << std::endl;

    return 0;
}
```

**Comment by Aaronepower** [comment]
dup of #62 . There is plan to support this, I just need to figure out how to handle in a language independent manner.
