### ISSUE TITLE
Badge webservice

### ISSUE THREAD

**Issue by louiz** [Aaronepower/tokei#112]
Would it be possible to release the code of the badge webservice (the thing running behind http://tokei.rs/b1/)?

I’d like to self host it on my server, and customize it to make it use my own self-hosted gitlab instance, instead of github.com or gitlab.com.

Thanks

**Comment by Aaronepower** [comment]
@louiz Hello, I don't there wouldn't really be a point the code is only 200 lines, and 90% is handling routes, caching and db management. Tokei is a library, and badge creation is done with the [`badge`](https://docs.rs/badge/0.1.0/badge/) crate, so it should be pretty easy to create. If you have any questions however feel free to continue to comment on this issue.
