### ISSUE TITLE
Sort languages by "name"

### ISSUE THREAD

**Issue by kaushalmodi** [Aaronepower/tokei#117]
It looks like the languages are currently sorted by the JSON key.

Can you please add an option to sort by the `"name" field in JSON.

For instance, I have modified languages.json locally with this:

```json
        "CShell":{
            "name":"Shell (csh/tcsh)",
            "base":"hash",
            "env":[
                "csh"
            ],
            "extensions":[
                "csh"
            ]
        },
```

I like to see the Shell scripts (tcsh, csh, bash, etc.) next to each other. At present I see:

```
 C Header               48        18485        17609          367          509
 Shell (csh/tcsh)      123         3224         1637         1034          553
 Clojure                 6           53           47            0            6
 <snip>
 Sass                    4          535          370           61          104
 Shell                 322        21468        12810         5426         3232
```

Would be nice to have sorting done by `"name" instead, or have an option for that.

Thanks!

**Comment by Aaronepower** [comment]
Thanks for filing an issue, I don't see the need for tokei to have this as the name of the shells are correct and it sorts correctly alphabetically. If you want to see every Shell variant you can easily see it with glob file patterns.

#### Bash
```bash
$ tokei **/*.*sh  *.*sh
```

#### Zsh
```zsh
$ tokei **/*.*sh
```

**Comment by kaushalmodi** [comment]
> name of the shells are correct

I am not contesting that.

I am just asking if sorting can be done based on the `"name"` field instead of the JSON key.

If you see above, the current sorting puts `Shell (csh/tcsh)` after `C Header` because the JSON key is `CShell`.

**Comment by kaushalmodi** [comment]
I just tried that.. got something unexpected:

```
> tokei "**/*.*sh" "*.*sh" --verbose
ERROR:tokei::utils::fs: entity not found
ERROR:tokei::utils::fs: entity not found
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
 Total                   0            0            0            0            0
-------------------------------------------------------------------------------
```

I use tcsh (have to), am on RHEL 6.6.

**Comment by Aaronepower** [comment]
Try it without the quotes.

**Comment by kaushalmodi** [comment]
Thanks, that worked.. but would have been nice to have stuff sorted by `"name"` in the full log.

For now, I just brute-force the sorting in my workarea by starting the keys for all shell scripts with "Shell": [commit](https://github.com/kaushalmodi/tokei/commit/ef6cbac5808b8e97e418e5f5b4e0f72e6bb19198).
