### ISSUE TITLE
Can we get a list of all files counted by tokei

### ISSUE THREAD

**Issue by kaushalmodi** [Aaronepower/tokei#118]
I ran tokei in one of my dirs and I got this:

```
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 BASH                    3          366          261           65           40
 <snip>
 Shell (csh/tcsh)       29         2343         1415          616          312
 <snip> 
------------------------------------------------------------------------------
 Total                 162        87153        60939        18373         7841
-------------------------------------------------------------------------------
```

Looking at `languages.json`, "*.bash" files are considered as BASH. But I do not have a single .bash file... `find . -name "*.bash"` returns nothing.

Also, it lists that I have 29 .csh files (I just [changed](https://github.com/kaushalmodi/tokei/commit/01d3cc63f2f953cec0c0f3b87bc81328dace3aad) the Language "name").. but `find . -name "*.csh" | wc -l` returns 36.

It would be interesting to get a list of all files that tokei counted under each language bin... something like "tokei --list=BASH".

**Comment by Aaronepower** [comment]
This is available through `tokei -f` which will print out the list of file relative to tokei.

**Comment by kaushalmodi** [comment]
Sorry for the noise, I missed the `-f` option in the help.

This is great!

```
BASH                    3          366          261           65           40
-------------------------------------------------------------------------------
 ./bash/tbgb                        205          142           39           24
 ./bash/tdw                          25            1           19            5
 ./bin/fzf-tmux                     136          118            7           11
```

**Comment by Aaronepower** [comment]
The reason tokei is counting those files is if you check the file line of those files it will be something like `#!/usr/bin/env bash` or similar. If a file has no extension tokei will look at that to determine what type of file it is.

**Comment by kaushalmodi** [comment]
Would you please consider adding a filter that would do help do something like:

```
tokei -f --lang="Plain Text"
```

**Comment by Aaronepower** [comment]
Can you make this a separate issue, and specify exactly what you expect such an option to do?

**Comment by kaushalmodi** [comment]
Done: https://github.com/Aaronepower/tokei/issues/119
