### ISSUE TITLE
Feature request: Option to list files only from the specified language(s)

### ISSUE THREAD

**Issue by kaushalmodi** [Aaronepower/tokei#119]
Currently `tokei -f` lists all the code files found by it. The number of files is in the order of 3k or 4k for my projects.

It would be interesting, though, to list only the files for specified languages.. let's say I want to see only the Markdown files.

So would you add a feature that would make something like this possible:

```
tokei -f --filter "Markdown"
```

.. or if I want to see all Markdown and Plain Text files:

```
tokei -f --filter "Markdown" --filter "Plain Text"
```

**Comment by twmb** [comment]
+1, but I think `-t` would be a decent flag to match `rg` file type filter.

**Comment by twmb** [comment]
I've opened https://github.com/Aaronepower/tokei/pull/145 to get the ball rolling on this one.

**Comment by Aaronepower** [comment]
@twmb Thanks for your PR! And congrats on your first contribution. I do not however see the value in this feature. It seems very niche I'd have to see a use case for it that isn't covered by reading in tokei's json or other output into your own script, or in the case of Rust using the library and just filtering the map.

**Comment by twmb** [comment]
Understandable! My use case is that I like to go into projects and see the complexity of the code I'm about to use (and in quite a lot of cases cases, read a good chunk of that code). For example, `tokei -tRust -f -etests -ewindows`.

It is possible to use the json, but I'd rather not write more _other_ code to use the tool. I think, instead, I'll frankenstein my fork to make even more specific for my use case.

Cheers - and feel free to do with #145 what you'd like!
