### ISSUE TITLE
Feature: exclude files from multiple directories

### ISSUE THREAD

**Issue by beatgammit** [Aaronepower/tokei#121]
I have a lot of third party code that I want to exclude, such as:

- git subrepos
- bower_components
- copy-pasta in a "vendor" directory

Unfortunately, tokei (6.0, Arch Linux) does not support multiple --exclude flags, so I can't specify more than one. I am please to say that it chugs through hundreds of thousands of extra lines of code in mere seconds 🥇

**Comment by Aaronepower** [comment]
This is available in master if you need it right now. Currently doing new tagged releases is blocked by #120

**Comment by tbu-** [comment]
The linked issue seems to be fixed, would it be possible to do a new release?

**Comment by Aaronepower** [comment]
A new release with the fixes has been uploaded.

**Comment by tbu-** [comment]
Github doesn't have the newest release yet – it's online on crates.io though.

**Comment by Aaronepower** [comment]
@tbu- Sorry, forgot to tag it so that the ci would deploy a release should be available soon now.

**Comment by tbu-** [comment]
Thanks! :)
