### ISSUE TITLE
Feature request: use filters when generating badge  

### ISSUE THREAD

**Issue by I60R** [Aaronepower/tokei#124]
Currently it counts lines from all sources in repo, but I want to exclude example project 
`?exclude=example`
or point tokei to specific directory
`https://tokei.rs/{host: values: github|gitlab}/{Repo Owner eg: Aaronepower}/{Repo name eg: tokei}/{Directory eg: src}`

**Comment by Aaronepower** [comment]
@I60R Hello the code for tokei_rs has been made public can you please move the issue over to it. https://github.com/Aaronepower/tokei_rs
