### ISSUE TITLE
Typescript + JSX

### ISSUE THREAD

**Issue by theduke** [Aaronepower/tokei#126]
Typescript files that contain JSX have the `.tsx` extension.

Those files are currently not recognized by tokei.

**Comment by Aaronepower** [comment]
Thanks for filing the issue! All that should be required is copying the `TypeScript` definition in `languages.json`, placing it below it, changing the extension, and adding `"name": "TypeScript JSX` property to it.

**Comment by theduke** [comment]
I'll do a PR In the evening.

**Comment by Aaronepower** [comment]
@theduke Hey, I was wondering if you ever got around to implementing this?
