### ISSUE TITLE
Proposal. Allowing style queries for badges

### ISSUE THREAD

**Issue by MaxGraey** [Aaronepower/tokei#127]
**Examples**
```
https://tokei.rs/b1/github/Aaronepower/tokei?style=flat
https://tokei.rs/b1/github/Aaronepower/tokei?style=flat-square
```

**Comment by Aaronepower** [comment]
Thanks for your issue! tokei.rs currently uses the [badge crate](https://github.com/onur/docs.rs/tree/master/src/web/badge) for generating badges. So any style changes would have to be available there first. Feel free to reopen this issue when they are available.
