### ISSUE TITLE
Exclude flag does not work as noted in help

### ISSUE THREAD

**Issue by PhnxRbrn** [Aaronepower/tokei#13]
The -e flag does not work.  The --Exclude only works if you set it equal to what you are excluding(--exclude=dirname/) but it should work like (--exclude dirname/) as noted in the help

**Comment by Aaronepower** [comment]
I've removed the rest args from exclude so now it should work, and if you want multiple values seperate them by a `,`.

**Comment by Luthaf** [comment]
> and if you want multiple values seperate them by a `,`

Is that a comma sign? If so, specifying multiple exclude does not work.
