### ISSUE TITLE
ruby comment supporting issue ?

### ISSUE THREAD

**Issue by si1kdd** [Aaronepower/tokei#134]
Hi, I just download tokei and i found there may have some bug about ruby comment lines couting.
(PS: I didn't read the source code)

And I just wrote a tiny programs:

```ruby 
x = 3
if x < 2
  p "Smaller"
else
  p "Bigger"
end

=begin
  Comments
  Comments
  Comments
  Comments
=end

while x > 2 and x < 10
  x += 1
end

# testing.
# total 8 comment lines.
p x
```
So this program just have 21 lines, and 8 comment lines,
but the reult of tokei is

```
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Ruby                    1           21            6           12            3
-------------------------------------------------------------------------------
 Total                   1           21            6           12            3
-------------------------------------------------------------------------------
```
Well, the total number of lines and blanks are correct , but the Code and Comments result seems weird ?
 I didn't read the source code,  seems the implementation is no correct.

My tokei version is 6.0.1, build from cargo.

Thx.

**Comment by Aaronepower** [comment]
Thank you for the issue! This has now been fixed in master and will be available in the next release(by the end of the week).
