### ISSUE TITLE
feature request: customize badge label

### ISSUE THREAD

**Issue by waldyrious** [Aaronepower/tokei#139]
For example in [tldr-pages/tldr](https://github.com/tldr-pages/tldr/blob/master/README.md) we're using the file count badge as a proxy to the number of pages in the collection. Ideally we'd want to only count files in the [pages directory](https://github.com/tldr-pages/tldr/tree/master/pages) (#124), but even with the current count, which is already a good approximation, we'd want to change the label from "Files" to "pages".

More generally, I think the label should be lowercased to match the majority of default badge labels (see e.g. https://shields.io)

**Comment by Aaronepower** [comment]
@waldyrious Hello the code for tokei_rs has been made public can you please move the issue over to it. https://github.com/Aaronepower/tokei_rs
