### ISSUE TITLE
parsing error in https://tokei.rs/b1/github

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [Aaronepower/tokei#154]
probably some parsing error (dot in the repo name):

this repo comes back with 403:
https://tokei.rs/b1/github/random-archer/nspawn.sh

while this repository (same account) works fine:
https://tokei.rs/b1/github/random-archer/dovecot_plugin_syncer

**Comment by Andrei-Pozolotin** [comment]
@Aaronepower please?

**Comment by Aaronepower** [comment]
@Andrei-Pozolotin Thanks for your issue! Sorry, I've been quite busy managing other projects. At the very least I plan to open source the server code soon so other eyes can review it.

**Comment by Aaronepower** [comment]
@Andrei-Pozolotin Hello, the code for tokei_rs has been made public can you please move the issue over to it. https://github.com/Aaronepower/tokei_rs
