### ISSUE TITLE
RFE: bump handlebars to 0.29

### ISSUE THREAD

**Issue by ignatenkobrain** [Aaronepower/tokei#157]
This is not very trivial due to

> [Changed] Align JSON path with original JavaScript implementation

And it fails with `thread 'main' panicked at 'Failed to generate languages! ERROR: RenderError(RenderError { desc: "Helper not defined: \"this\"", template_name: None, line_no: None, column_no: None, cause: None })', build.rs:40:8`

**Comment by ignatenkobrain** [comment]
I need this for proper package of tokei in Fedora.

**Comment by Aaronepower** [comment]
Thank you for filing this issue, is this still a problem? Your PR that bumps the version to 0.29 seems to build just fine.

**Comment by ignatenkobrain** [comment]
@Aaronepower I've got help from developer of handlebars, so no issue ;)

**Comment by ignatenkobrain** [comment]
#158 it is

**Comment by Aaronepower** [comment]
closed by #158
