### ISSUE TITLE
Add functionality to lines of code

### ISSUE THREAD

**Issue by PhnxRbrn** [Aaronepower/tokei#16]
Add capability to report both physical lines of code and logical lines of code

**Comment by Aaronepower** [comment]
Can you provide examples of languages that have the difference I know that FORTRAN does, but is there one in particular you're thinking about?

**Comment by PhnxRbrn** [comment]
SQL for instance can multiline code where  for instance has 10 physical lines for one statement with the last line ending with a ; so it counted as 1 logical line of code. Also most C derived languages follow the measurements from HTTPS:

**Comment by PhnxRbrn** [comment]
https://en.wikipedia.org/wiki/Source_lines_of_code

**Comment by Aaronepower** [comment]
What would be the purpose for this? As this is a program for humans, I'm not really seeing the use case for why someone would need to see the difference.

**Comment by PhnxRbrn** [comment]
For instance at my job when we work on releases we provide the the delta of the logical lines of code that have changed not the physical lines

**Comment by PhnxRbrn** [comment]
It is a metric most companies I have work for use

**Comment by Aaronepower** [comment]
I've been thinking about this. Implementing this is a lot bigger than simply going something like `file.split(";")`. If I did this than I would have also change how to detect the single comments. Also this would work fine for things like SQL where a single line of execution is spread over multiple lines, but what about the reverse? What about this?





```


let x = 1; let y = 2;

let z = 3;


```





Is that two lines or three? Now while that use case is simple what about languages where you can comma variable declarations? Or other weird declarations




```


let x, y, z;




Let x = y = 5;

```





Is this two or five? Or other common use case, for loops.




```


for (let x =0; x < y; x++) {

  y-x;

}

```





What about languages like JavaScript or Swift? Where the finished statement is unclear without an AST?.

**Comment by PhnxRbrn** [comment]
This may be not fully worth the effort then with all the different languages then.  There is no point to do it to only some of the languages and not all of them.  Should we leave this open in case someone wants to fully take the effort in the future or should it just be closed?

**Comment by Aaronepower** [comment]
I'm going to close it as being out of scope for this project. Even if someone did implement it, I'd probably want it to be standalone from this.
