### ISSUE TITLE
--files truncates paths at 24 characters

### ISSUE THREAD

**Issue by chris-morgan** [Aaronepower/tokei#160]
Tokei seems to try to fit its output in 79 columns, regardless of the terminal configuration (my terminal is 120 columns wide) or whether it’s being piped to something (at which point I would generally expect it to throw away any capping of line width, but wouldn’t quibble if it didn’t provided there was a command line argument).

Platform: Windows, Command Prompt.

The primary effect of this is that `tokei --files` truncates paths, showing only the last 24 characters of them; take this example in Rust’s libstd, for example:

```
C:\code\rust\src\libstd>tokei -f
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Rust                  254        86150        48404        29682         8064
-------------------------------------------------------------------------------
[…]
 .\sys\windows\ext\ffi.rs           147           29          110            8
 .\sys\windows\ext\fs.rs            488           84          379           25
 .\sys\windows\ext\io.rs            209          136           52           21
 .\sys\windows\ext\mod.rs            44           21           19            4
 |s\windows\ext\process.rs          119           84           19           16
 .\sys\windows\ext\raw.rs            21            7           10            4
 |ys\windows\ext\thread.rs           31           16           10            5
 |\redox\net\dns\answer.rs           22           11            9            2
 |sys\redox\net\dns\mod.rs          215          177            9           29
 |s\redox\net\dns\query.rs           18            7            9            2
 |edox\syscall\arch\arm.rs           83           58           10           15
 |edox\syscall\arch\x86.rs           83           58           10           15
 |x\syscall\arch\x86_64.rs           84           59           10           15
 |trace\printing\dladdr.rs           45           32            9            4
 |acktrace\printing\mod.rs           43           28            9            6
 |\tracing\backtrace_fn.rs           48           25           19            4
[…]
```

This renders the output useless for machine reading.

I see three parts to fixing this:

1. Make it use the actual terminal width rather than a blind 79 columns (if it’s already supposed to be doing that, then change this to “detect console width on Windows”);
2. Add a command-line argument to uncap the width (like `ps -ww`);
3. Decide what to do when it is piped or the width cannot be determined (for reference, `ps` says of such cases that “the output width is undefined (it may be 80, unlimited, determined by the TERM variable, and so on)”, which is not necessarily a good situation).

**Comment by Aaronepower** [comment]
@chris-morgan Thank you for this issue! I think it should probably be automatically detected at runtime. I'm not worried about what happens when the output is being piped as that isn't the best or correct way to read tokei output.

Do you know of a crate that can handle outputting to the full width?

**Comment by chris-morgan** [comment]
I haven’t looked into the crate being used for formatting at all.

Why do you say that piping isn’t the best or correct way to read tokei output? What’s the alternative?

**Comment by Aaronepower** [comment]
@chris-morgan I mean specifically tokei’s default output is designed for humans and not guaranteed to be deterministic and can change between minor or patch versions. Tokei’s `—output` argument is guaranteed to only break during major versions and is available in various formats.
