### ISSUE TITLE
Specify source path for badge

### ISSUE THREAD

**Issue by povilasb** [Aaronepower/tokei#162]
Is there a way to specify source code path inside repository when requesting for badge?
E.g. `https://tokei.rs/b1/github/povilasb/pyigd?category=code&path=igd`

Currently it uses the root project directory, but that's not where my source files are at.

**Comment by Aaronepower** [comment]
@povilasb Hello, the code for tokei_rs has been made public can you please move the issue over to it. https://github.com/Aaronepower/tokei_rs
