### ISSUE TITLE
Print unsupported serialization format message at start

### ISSUE THREAD

**Issue by notramo** [Aaronepower/tokei#164]
Currently, `tokei` counts all the files, then when it finishes this task, prints an error message if it was compiled without the requested serialization language.
It should print it at the start of execution, without counting the files.

**Comment by Aaronepower** [comment]
@notramo Hello and thank you for this issue. I cannot replicate this can you please provide what command you used and what version of tokei you are using?

**Comment by notramo** [comment]
I am using `master` on Linux.
When it is compiled **without** any serialization language, it prints this message **after** counting files:
```

    This version of tokei was compiled without any serialization formats, to
    enable serialization, reinstall tokei with the features flag.

        ALL:
        cargo install tokei --features all

        JSON:
        cargo install tokei --features json

        CBOR:
        cargo install tokei --features cbor

        YAML:
        cargo install tokei --features yaml

        CBOR:
        cargo install tokei --features cbor

```

When it is compiled with **some** serialization language, but **not with all**, it crashes when specifying a format it don't support (e.g. compiled with JSON and YAML, but running with `-o cbor` or `-o toml`) 
The following is compiled with `--features "json yaml"`:
```
thread 'main' panicked at 'Couldn't convert to TOML: ()', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

If it gets an invalid serialization language with the `-o` option (e.g. `tokei -o xml`), it prints an error message:
```
error: 'xml' isn't a valid value for '--output <output>'
	[values: cbor, json, toml, yaml]


USAGE:
    tokei --output <output>

For more information try --help
```
*The executable in this example was compiled only with CBOR support, but it says that it accepts JSON, YAML, and TOML also.*

### Expected behaviour:
* If the executable was compiled **without** any serialization support, it should print the same message as it prints currently, **but without counting lines**.
* If the executable was compiled with **some** serialization format, *but not with all*, and the format given with `-o` is **valid**, but not supported, it should inform the user:
```
    This version of tokei was compiled with support only for these serialization languages: TOML, JSON.
    To enable YAML, reinstall tokei with the `yaml` feature enabled.

        cargo install tokei --features yaml
        (or if you want the currently supported formats also)
        cargo install tokei --features "json toml yaml"
```
* If the given serialization format is **invalid**, it should inform the user about it:
```
Error: 'html' isn't a valid value for serialization format.
Currently supported formats: json, toml.
To enable CBOR, or YAML, reinstall tokei with the 'yaml' or 'cbor' feature enabled.

    cargo install tokei --features "yaml json toml"
```
