### ISSUE TITLE
Add averege line size metric

### ISSUE THREAD

**Issue by non-descriptive** [Aaronepower/tokei#182]
I think it's good way to analyse code complexity (rule 30/60/80) a bit and show extra column with average line size per file type

**Comment by Aaronepower** [comment]
Thank you for this issue, could you expand on what you mean by average line size?

**Comment by non-descriptive** [comment]
sum of symbol count in file without blank lines and comments divided by total file lines without blank lines and comments.

**Comment by Aaronepower** [comment]
Closing due to lack of motivation for the feature or clear reason for it. Feel free to re-open if you can expand further on the use cases of this feature and why it requires a another column.
