### ISSUE TITLE
Consider shebang line

### ISSUE THREAD

**Issue by FichteFoll** [Aaronepower/tokei#186]
Some files don't have an extension but their file type can be inferred from the shebang line. This *could* affect performance, so it might be wise to hide this functionality behind a flag.

Example:

```
#!/usr/bin/env python3.6
```

**Comment by Aaronepower** [comment]
@FichteFoll The shebang line is already considered! I don't think `python` has been set specifically, you can check out how to set it by looking in [languages.json](https://github.com/Aaronepower/tokei/blob/master/languages.json#L112) and looking at other languages with a `"env"` property.

**Comment by FichteFoll** [comment]
Would just `python` suffice here (i.e. does it do a submatch) or do I need all the version variants too?

**Comment by Aaronepower** [comment]
@FichteFoll It needs to a be a full match, I would just put in `python`, `python3`, `python3.6`, and `python2.4`.
