### ISSUE TITLE
Consider building release artifacts with some features enabled

### ISSUE THREAD

**Issue by Ryman** [Aaronepower/tokei#189]
The [releases](https://github.com/Aaronepower/tokei/releases) are currently built without any serialization, so if you download them and want to use it in a workflow you have to go through a full install. Having at least json available would be great!

**Comment by Aaronepower** [comment]
@Ryman That's a bug, GitHub releases should include all serialisation options, the reason for the separation is that they heavily lengthen install time when installing crates.io

**Comment by Aaronepower** [comment]
This should now be fixed in the CI and future releases will include all serialisation formats.
