### ISSUE TITLE
tokei::utils::fs: partial error

### ISSUE THREAD

**Issue by hoangtranwork** [Aaronepower/tokei#198]
I got the above error in a particular case:
- On macOS
- run tokei on a sub-directory of a repo
- the .gitignore file (in the root of the repo) has special `@` attribute when shown with `ls`

Note:
- Running tokei from the root of the repo is ok
- Trying to delete then re-create the .gitignore so that it does not have '@' next to it in `ls`, after that tokei run ok

https://www.dropbox.com/s/09wqo3hmbny1krn/Screenshot%202018-02-25%2022.22.54.png?dl=0

**Comment by Aaronepower** [comment]
@hoangtranwork Thank you for this issue! However `tokei` doesn't handle `.gitignore`, it leaves that to the [ignore](https://github.com/BurntSushi/ripgrep/ignore) crate which lives on the [ripgrep repo](https://github.com/BurntSushi/ripgrep), I'd recommend filing this [issue over there](https://github.com/BurntSushi/ripgrep/issues). Thanks again!

**Comment by hoangtranwork** [comment]
@Aaronepower thank you for quick response.

Not handling .gitignore is ok to me, it was just my observation that there's error running tokei in some case.

Updated: I've just re-check this again and it seems that it has the same error running in sub directory, regardless of how .gitignore attribute is. (https://asciinema.org/a/4QeAJbVtUFHJbpvClUhPFN25A)

**Comment by Aaronepower** [comment]
@hoangtranwork Sorry I think I may have been unclear. This is definitely a bug, but `tokei` doesn't have the code that checks for `.gitignore` it uses a library called `ignore`. So they [need this issue](https://github.com/BurntSushi/ripgrep/issues).

**Comment by hoangtranwork** [comment]
@Aaronepower ah, ok. I'm not sure if this is still related to .gitignore or not. Btw, your link is pointing to ripgrep repo.

**Comment by Aaronepower** [comment]
@hoangtranwork ignore is maintained in the ripgrep repo.

**Comment by hoangtranwork** [comment]
So it turns out I got an invalid pattern in my .gitignore file (`**`) and this is a discussed issue in `ignore` project. Thank you for pointing me to the right direction @Aaronepower
