### ISSUE TITLE
Fortran, my friend!

### ISSUE THREAD

**Issue by Luthaf** [Aaronepower/tokei#2]
There are multiple issue with Fortran that precent it from being used with tokei. First, two syntaxes exists: the modern (or free-form) one, and the legacy (or fixed-form) one. They can be considered as two different languages in tokei. The main issues are:

1. Multiple file extension. For modern syntax, are recognised the following file extensions: `.f90`, `.F90`, `.f95`, `.F95`, `.f03`, `.f08` (and maybe `.F03` and  `.F08`, but I never found them). For the legacy syntax, you can use `.f`, `.F`, `.f77`, `.F77`, `.fpp`, `.FPP`.
2. Multiple comments characters: in legacy syntax, the `c` or `C` or `*` characters indicate a comment, but only if found in the columns from 1 to 7.
3. Line continuations characters: in all syntaxes, the `&` character is a line continuation, and it is used a lot in legacy syntax, due to the 72 characters by line limit.

So, how can I bypass these issues ?

1. Can it be a way to group together multiple extension for one language in the finale countdown ?
2. Maybe use regex for comments detection, if needed ?
3. I believe this exist for lot of other languages, so it may be useful to have a `line_continuation` field in the Language struct. But I do not know the usual way of doing it in cloc programs, to ignore or to merge continuated lines.

**Comment by Aaronepower** [comment]
Well the two different syntaxes should get two separate categories, as I think you'd want to know how much legacy code you have, and how much modern code.




Can you explain the comment structure? Perhaps provide an example?  I've never seen anything like that.




From what I'm getting is that line continuation is for the machine, not the human. So to a human a line with a line continuation, is still a separate line in your text editor, it just says that the next line also works on the code written here. So I don't think it is necessary.







I specifically chose not to use regex, as it is a lot harder to work with, and a lot more edge cases over directly interpreting the lines. And I've found that [CLOC](http://cloc.sourceforge.net/) which uses regex to be inaccurate.

**Comment by Luthaf** [comment]
> Well the two different syntaxes should get two separate categories, as I think you'd want to know how much legacy code you have, and how much modern code.

I would like to have this too, but how can I merge the results for different files extensions? I would like to get the results for `f90` and `f03` merged together.

> Can you explain the comment structure? Perhaps provide an example?  I've never seen anything like that.

My Fortran is pretty rusty, and the real rule for fixed-form is that a comment is stated by one of the `c`, `C`, `*` or `!`, but only if they are found in the first column of text. See http://fortranwiki.org/fortran/show/Fixed+form+layout for an example, and here is a simpler one:

```f77
c      this is a comment
        a = 3 + 5
! another comment
        c  = "not a comment!"
        * "not a comment!"
* this is one
```

> From what I'm getting is that line continuation is for the machine, not the human. So to a human a line with a line continuation, is still a separate line in your text editor, it just says that the next line also works on the code written here. So I don't think it is necessary.

Ok, I am fine with this point of view.

**Comment by Aaronepower** [comment]
Currently there is no way for a language to have multiple extensions. However file extensions aren't case sensitive so `.fpp`, and `.FPP` are the same. What is the latest extension of both? I'll set the them as both, and then once I've added multiple extension support 'I'll revisit this issue, and add in the other less popular FORTRAN extensions.

**Comment by Luthaf** [comment]
Here is a tentative of classification:

### Modern syntax

Most popular: `.f90`

Other valid: `.f95`, `.f03`, `.f08`

Indicating the use of `cpp` preprocessor: `.F90`, `.F95`, `.F03`, `.F08`

### Legacy syntax

Most popular: `.f`

Other valid: `.f77`

### Legacy syntax, with preprocessor

I do not know the most popular extension, the valid one are `.F`, `.fpp`, `.FPP`
