### ISSUE TITLE
Recognize #!

### ISSUE THREAD

**Issue by notramo** [Aaronepower/tokei#208]
Some scripts (mostly those are in `/bin`) don't have an extension, instead they have a hashbang.
These scripts are not recognized by `tokei`, so the result is incorrect.

**Comment by Aaronepower** [comment]
Shebang's are recognised by tokei, if it's from `#!/usr/bin/env` add the `env` property in `languages.json` otherwise it needs to be added in [`language_type.hbs.rs`](https://github.com/Aaronepower/tokei/blob/master/src/language/language_type.hbs.rs#L235).

**Comment by notramo** [comment]
Why aren't shebangs recognised by `tokei` similarly as `#!/usr/bin/env` is recognised? It should search for the basename of the interpreter in the language list.

**Comment by Aaronepower** [comment]
@notramo Because it needs to whole word check I wouldn't want something like `#!/usr/bin/pythontoy` being recognised as `python`.

**Comment by notramo** [comment]
Why would `#!/usr/bin/pythontoy` be recognised as Python?
Is `#!/usr/bin/env pythontoy` recognised as Python?
