### ISSUE TITLE
Unrecognized/unsupported filetypes

### ISSUE THREAD

**Issue by notramo** [Aaronepower/tokei#209]
If a file don't have either an extension or a shebang, `tokei` should count it as plain text.
If a file has an extension or a shebang, but it is not known by `tokei`, it should count it as `Unsupported`, and use the same rules as used with plain text (every line is code).

**Comment by Aaronepower** [comment]
Thank you for this issue! I don't agree that `tokei` should count unrecognised files as Plain text as that can be misleading. If you want to know which files aren't being counted run the command as `tokei -v` which will print out warnings of what it couldn't recognise.

**Comment by notramo** [comment]
And what do you think about counting them as `Unsupported` ?

**Comment by notramo** [comment]
What do you think about implementing it with a command line option?

**Comment by Aaronepower** [comment]
@notramo What does counting `Unsupported` add to the value of `tokei`?

**Comment by notramo** [comment]
It would indicate to the user that there is more code in the counted directory, but  `tokei` can't determine what language is it.

**Comment by Aaronepower** [comment]
@notramo It isn't necessarily be code though this would count binary files, pdfs, docs.

**Comment by notramo** [comment]
Of course, I meant only text files. (to be accurate: _unsupported **language**_ (only text files), not _unsupported **filetype**_)
The command line option would turn on a filetype recognition if it don't have an extension,  and if it is a text file with unknown language, it would count it as `Unsupported`.

**Comment by Aaronepower** [comment]
@notramo What information does `Unsupported` give that `tokei -v` doesn't?

**Comment by notramo** [comment]
It would show how many lines does the unsupported files have, not only what files are not supported.
