### ISSUE TITLE
Code and comment on the same line

### ISSUE THREAD

**Issue by notramo** [Aaronepower/tokei#210]
`tokei` should have an option that enables counting the lines that has comments at the end of the line as both code and comment.
So this code would be counted as 1 line of code and 1 line of comment:
```crystal
puts "this is a line of code" # and this is a line of comment
```

**Comment by Aaronepower** [comment]
@notramo I think this is a change that would require changing a lot of the opinions of `tokei`. I don't agree that `tokei` should go in that direction. I feel like if you want that option you want something that parses and counts a lot more in depth than `tokei` for the language.
