### ISSUE TITLE
Ignore generated code

### ISSUE THREAD

**Issue by mafredri** [Aaronepower/tokei#215]
This is something of a feature request / discussion.

I have a few Go projects with generated code, and it would be nice to be able to easily filter out the noise. I'm curious if this, let's call it call it language-specific intelligence, is something you have been considering.

In the case of Go there is a standard code comment to mark a file as generated: `^// Code generated .* DO NOT EDIT\.$`. As described in https://golang.org/s/generatedcode.

(As a side note, Go also has a `vendor` folder with vendored code, also to be ignored in most cases).

That's not to say I can't quite easily accomplish this myself on the command line:

```console
$ tokei . --exclude vendor $(print -- '--exclude '${^$(rg -l '^// Code generated by')})
```

But the thought of `tokei` making smart default choices is quite alluring. Thoughts?

PS. Tokei is crazy fast, I love it :)!

**Comment by Aaronepower** [comment]
@mafredri Thank you for this issue! I have never written go, so I don't know how code is typically generated. Is there any reason this couldn't be solved by having a `.ignore` file which includes the paths of the generated code?

**Comment by mafredri** [comment]
Go code is mostly generated by programs, there is no built-in way in the language to generate code. You make a fair point, but in the case of Go, generated code is typically committed into VCS and as such it doesn't make sense to maintain ignore files. Most Go tools also detect generated code (via the code comment described above) and change their behavior. For example `golint` happily skips all generated code because it is not held to the same standard.

It's very likely that Go is the only language where these rules apply, so I can totally understand if you feel it doesn't have a place in `tokei`, but happy to hear your thoughts on the matter :).

**Comment by Aaronepower** [comment]
@mafredri Sorry I may have been unclear, as far as I know `.ignore`(not `.gitignore`) and the files listed are committed to VCS but they will be ignored by tokei.

**Comment by Aaronepower** [comment]
@mafredri It may be uncommon, but so is routinely using tokei to count your source code! 😃 The way I see it is `.ignore` is zero cost way to consistently ignore these types of files that works for every language not just Go. Adding in this would prioritise Go in a way that'd make it perform worse since it'd have to read the first line of every Go file and then perform a regex check to see if it's generated.

**Comment by mafredri** [comment]
To be fair, it would only penalize Go parsing, and it needn't be as complicated as a regex, simple prefix / suffix checking would suffice (e.g. like in https://github.com/golang/lint/blob/85993ffd0a6cd043291f3f63d45d656d97b165bd/lint.go#L118-L134). I'm not really versed in how `tokei` does it's parsing, but I don't see that it would be much of an impact.

Oh, and parsing the first line would not be sufficient, the comment is allowed to appear on any line of the file (although it's commonly placed close to the top).

All that being said, I just wanted to bring this up for discussion. If you feel it doesn't have a place in `tokei`, that's fine as well.
