### ISSUE TITLE
Panic when using uninstalled output format if any other formats are installed

### ISSUE THREAD

**Issue by kballard** [Aaronepower/tokei#221]
If I install tokei with no output formats, attempting to use any gives me an error message explaining how to reinstall it with support for the formats. However, if I install it with one format, and then try to use a different format, instead of printing an error message tokei just panics.

```
> cargo install tokei --features json
[…]
> tokei -o toml src
thread 'main' panicked at 'Couldn't convert to TOML: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

tokei 7.0.1

**Comment by Aaronepower** [comment]
@Ryman Could you have a look at this and #220 ?

**Comment by Ryman** [comment]
I had an open question in the PR about parsing toml being busted, but it looks like my changes were not part of 7.0.1 (and these issues *should* be fixed by them)?

**Comment by Aaronepower** [comment]
@Ryman 7.0.1 was released before your PR. 7.0.2 was released today and should have those changes.

**Comment by Aaronepower** [comment]
Closing this as tokei does now have an error message explaining formats not being available, this information is also available through `--version`
