### ISSUE TITLE
question: how does this compare to sloccount?

### ISSUE THREAD

**Issue by rudolfolah** [Aaronepower/tokei#226]
would be good to add a section on that in the README; for example is it more accurate or just faster or a nicer looking output?

thanks!

**Comment by Aaronepower** [comment]
@rudolfolah I've never used sloccount myself, so I don't know if it's more or less accurate. It seems that they are just as accurate from [this article](https://boyter.org/posts/sloc-cloc-code/) and tokei is significantly faster. I currently am too busy to write up a comparison, if anyone can provide details of sloccount. I'd be happy to compare those to tokei and put that in the README.

**Comment by rudolfolah** [comment]
@boyter Thanks, that's thorough! Personally, points 3, 4, 5, and 11 are a good reason to use sloccount but that's neither here nor there. It might be cool to put this into the README for others (and maybe mention cloc or other tools?)

I'll try out tokei on my local codebases to see what other differences there are.

**Comment by boyter** [comment]
@rudolfolah No problem. 

Just to point out the alternatives, full list https://boyter.org/posts/sloc-cloc-code/

For point 3 you can use gocloc https://github.com/hhatto/gocloc which will be faster than sloccount and probably about as accurate. For 5 and 11 you can use https://github.com/boyter/scc/ which is about as fast as tokei. For point 4 that's more of a personal/company choice thing.

Actually point 11 is the reason I even added COCOMO into scc as I needed to add that logic into searchcode.com anyway and it was an easy thing to move across.

**Comment by Aaronepower** [comment]
Closing this as I feel it has been answered specifically and if anyone is interested in performance comparison have a look at [COMPARISON.md](https://github.com/Aaronepower/tokei/blob/master/COMPARISON.md).
