### ISSUE TITLE
Docstrings in Clojure are counted as code

### ISSUE THREAD

**Issue by heyarne** [Aaronepower/tokei#229]
I know that there are multiple issues regarding this problem, but always mentioning python as an example (#100, #185). I thought it would be worth noting that the same problem exists in Clojure:

``` clj
(defn hello-world
  "I am documenting this function"
  ;; I am a comment
  (println "I am a string"))
```

Output of tokei:
```
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Clojure                 1            4            3            1            0
-------------------------------------------------------------------------------
 Total                   1            4            3            1            0
-------------------------------------------------------------------------------
```

**Comment by Aaronepower** [comment]
Thank you for this issue, unlike the python issues I don't think tokei can correctly count Clojure doc comments as there is nothing syntactically different from a regular string, and it would require a parser in order to differentiate between them.
