### ISSUE TITLE
Nginx badge server returns 404 for project with name that ends in file extension

### ISSUE THREAD

**Issue by Nektro** [Aaronepower/tokei#231]
See
https://tokei.rs/b1/github/nektro/modules.js
https://github.com/Nektro/modules.js
or
https://tokei.rs/b1/github/mrdoob/three.js
https://github.com/mrdoob/three.js

**Comment by Aaronepower** [comment]
Thank you for this issue. I'm marking this as a duplicate of https://github.com/Aaronepower/tokei_rs/issues/1
