### ISSUE TITLE
Failed to compile tokei v7.0.3

### ISSUE THREAD

**Issue by mikong** [Aaronepower/tokei#243]
I tried installing tokei on my mac (High Sierra 10.13.6) using the recommended Cargo command in the README:

```
cargo install tokei
```

My cargo and rust version:

```
cargo 0.26.0 (41480f5cc 2018-02-26)
rustc 1.25.0 (84203cac6 2018-03-25)
```

I encountered the following errors:

```
   Compiling tokei v7.0.3
error[E0658]: use of unstable library feature 'fs_read_write' (see issue #46588)
   --> build.rs:122:8
    |
122 |     Ok(fs::write(Path::new(&out_dir).join("tests.rs"), string)?)
    |        ^^^^^^^^^

error[E0580]: main function has wrong type
  --> build.rs:14:1
   |
14 | fn main() -> Result<(), Box<error::Error>> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected (), found enum `std::result::Result`
   |
   = note: expected type `fn()`
              found type `fn() -> std::result::Result<(), std::boxed::Box<std::error::Error + 'static>>`

error: aborting due to 2 previous errors
```

The `cargo install` command was able to compile tokei's dependencies (61 crates were compiled before the `Compiling tokei` part). It only failed as it tried to compile tokei.

Please let me know if you need any additional information about my local machine.

**Comment by Aaronepower** [comment]
@mikong Thank you for your issue! Tokei only supports the latest stable release for compiling from source. You are using `1.25.0` when `tokei` is using `1.26.0` features. I would recommend updating your rust installation to `1.28.0` or if there is a specific reason you can't upgrade to use the compiled versions available in the GitHub releases.
