### ISSUE TITLE
polyglot two-times faster than tokei? 

### ISSUE THREAD

**Issue by gnzlbg** [Aaronepower/tokei#247]
From: https://github.com/vmchale/polyglot

> polyglot: 143.2 ms
> loc: 171.8 ms
> tokei: 304.6 ms

It might be interesting to look at which optimizations they are using.

**Comment by Aaronepower** [comment]
Well Polyglot is written in a language I'm completely unfamiliar with, and I can't seem to install it at the moment to measure accuracy. I've filed an issue about that and once that is resolved I can look more closely at polyglot.

**Comment by gnzlbg** [comment]
In https://github.com/vmchale/polyglot#building-for-hacking there seem to be instructions for building it on MacOS.

**Comment by boyter** [comment]
As far as I can tell this is only true for < 8 core machines.

When you scale out to 8, 16 or 32 there is no situation for which polyglot is faster. For example see the following https://boyter.org/posts/sloc-cloc-code-performance/#benchmarks where polyglot was only comparable on speed for the redis code-base due to it being very small.

Is this a case worth optimizing for? I would say no. CPU's are only getting more and more cores, and polyglot is not very accurate for most tests I have tried.

**Comment by boyter** [comment]
@gnzlbg Feel free to try it out. I can say for sure that on any machine with 8 cores or more that tokei will be faster, but this holds true for machines with less cores too.

For example, see the below on a 4 core system.

```
$ hyperfine "~/polyglot redis"
Benchmark #1: ~/polyglot redis
  Time (mean ± σ):     219.3 ms ±  15.0 ms    [User: 27.1 ms, System: 490.3 ms]
  Range (min … max):   203.2 ms … 252.8 ms

$ hyperfine "tokei redis"
Benchmark #1: tokei redis
  Time (mean ± σ):     167.7 ms ±   8.9 ms    [User: 136.2 ms, System: 487.0 ms]
  Range (min … max):   156.8 ms … 181.1 ms
```

As for why is polyglot faster? As mentioned it is not accurate. For example consider the following very simple case of a very stupid python program,

```
# This is a comment
import this
# Another comment
```

Lets compare polyglot to tokei

```
$ polyglot .
-------------------------------------------------------------------------------
 Language             Files       Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Python                   1           3            2            1            0
-------------------------------------------------------------------------------
 Total                    1           3            2            1            0
-------------------------------------------------------------------------------

$ tokei .
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Python                  1            3            1            2            0
-------------------------------------------------------------------------------
 Total                   1            3            1            2            0
-------------------------------------------------------------------------------
```

In short, the answer it is doing less. Keep in mind that the tools both produce different results for the above so this is not a fair comparison. I did write one though which for both polyglot and tokei produce the same results. You can create this test using this script https://github.com/boyter/scc/blob/master/examples/create_performance_test.py

When run on my 4 core machine using polyglot and tokei against two of the directories the script creates,

```
$ hyperfine "~/polyglot 1"
Benchmark #1: ~/polyglot 1
  Time (mean ± σ):     654.8 ms ±  10.8 ms    [User: 31.1 ms, System: 1073.4 ms]
  Range (min … max):   636.3 ms … 668.8 ms

$ hyperfine "tokei 1"
Benchmark #1: tokei 1
  Time (mean ± σ):     467.4 ms ±  18.8 ms    [User: 112.3 ms, System: 1704.6 ms]
  Range (min … max):   445.9 ms … 497.9 ms

$ hyperfine "~/polyglot 2"
Benchmark #1: ~/polyglot 2
  Time (mean ± σ):      1.796 s ±  0.045 s    [User: 193.4 ms, System: 5050.6 ms]
  Range (min … max):    1.712 s …  1.850 s

$ hyperfine "tokei 2"
Benchmark #1: tokei 2
  Time (mean ± σ):      1.049 s ±  0.042 s    [User: 546.5 ms, System: 5181.3 ms]
  Range (min … max):    0.976 s …  1.101 s
```

For the above benchmarks tokei and polyglot are producing the same results. Feel free to rerun on a machine with less then 4 cores to see what impact that has. Even with 4 cores tokei is usually faster.

In short, the comparison is not a fair one. When doing the same work and producing the same output tokei is faster, even on a 4 core system, and I suspect might still be true on a 2 core.

**Comment by Aaronepower** [comment]
I think @boyter has sufficiently answered the question proposed so I'm closing this.
