### ISSUE TITLE
Ability to use with non-filesystem files

### ISSUE THREAD

**Issue by kornelski** [Aaronepower/tokei#250]
I'd like to analyze files that are in tarballs and bare git checkouts, on the fly, without copying these files to disk.

Could you expose an interface that would make it possible? e.g.

```rust
let mut tokei = Tokei::new();
for imaginary_path in fake_filesystem {
    tokei.add_file(imaginary_path, bytes_of_file_body); // e.g. "file.rs", &[u8]
}
let counts = tokei.totals();
```

**Comment by Aaronepower** [comment]
Thank you for your issue! Is there a reason creating a fake directory using `tempfile` wouldn't be satisfactory?

**Comment by kornelski** [comment]
It's a performance issue. I've already got these files in memory, and there's lots of them.

**Comment by Aaronepower** [comment]
The only problem I've found when I was looking through on adding it, which is that `Stats` requires a `DirEntry`, I don't really want to change that just for this case. Is there a way that without copying you could generate temp files?

**Comment by kornelski** [comment]
Thanks for looking into this. That's a bummer with `DirEntry`. 

I'm analysing all crates on crates.io and their git checkouts, so that's a lot of temp files. I could set up a ramdisk to avoid churn on disk, but that's a long way around.

**Comment by Aaronepower** [comment]
I could still expose a `parse_from_str(DirEntry, &str)` and you could just get one DirEntry and reuse that. It's a bit hacky but beyond adding a way to create a `DirEntry` in `ignore`.

**Comment by kornelski** [comment]
Yes, something like that could work.

There's `DirEntry::new_stdin()` which I could use to fake one for `Stats`. Or if breaking API is an option, then you could change `Stats` to contain `Option<DirEntry>` or `PathBuf` instead.

**Comment by Aaronepower** [comment]
Alright, I've added the `parse_from_str` function to master. Try it and see how well it works for you.

**Comment by Aaronepower** [comment]
@kornelski Due to issues found in #251 I've decided to switch back to `PathBuf` and just deal with the extra allocation for now while waiting for my PR to turn a DirEntry into a PathBuf to be accepted.

**Comment by kornelski** [comment]
So unfortunately it still shipped with the `DirEntry` requirement. I haven't noticed previously that `DirEntry::new_stdin()` is a private method :(

I've ended up doing:

```rust
WalkBuilder::new("-")
                        .parents(false).ignore(false)
                        .git_global(false).git_ignore(false).git_exclude(false)
                        .build()
                        .next()
                        .unwrap()
                        .unwrap();
```

to make a fake stdin `DirEntry`. Fortunately it's cloneable.
