### ISSUE TITLE
Building v8.0.0 with "--features all" is failing

### ISSUE THREAD

**Issue by dbast** [Aaronepower/tokei#251]
- Rust: 1.28.0
- Command: cargo install tokei --verbose --features all 
(--features json also fails)
- Environment: Mac OS 10.13.6 (same error on Linux and Windows)

Error:
error[E0277]: the trait bound `ignore::DirEntry: serde::Deserialize<'_>` is not satisfied
 --> src/stats.rs:6:35
  |
6 | #[cfg_attr(feature = "io", derive(Deserialize, Serialize))]
  |                                   ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `ignore::DirEntry`
  |
  = note: required by `serde::de::SeqAccess::next_element`

error[E0277]: the trait bound `ignore::DirEntry: serde::Deserialize<'_>` is not satisfied
 --> src/stats.rs:6:35
  |
6 | #[cfg_attr(feature = "io", derive(Deserialize, Serialize))]
  |                                   ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `ignore::DirEntry`
  |
  = note: required by `serde::de::MapAccess::next_value`

error[E0277]: the trait bound `ignore::DirEntry: serde::Serialize` is not satisfied
 --> src/stats.rs:6:48
  |
6 | #[cfg_attr(feature = "io", derive(Deserialize, Serialize))]
  |                                                ^^^^^^^^^ the trait `serde::Serialize` is not implemented for `ignore::DirEntry`
  |
  = note: required by `serde::ser::SerializeStruct::serialize_field`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
error: failed to compile `tokei v8.0.0`, intermediate artifacts can be found at `/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK`

Caused by:
  Could not compile `tokei`.

Caused by:
  process didn't exit successfully: `rustc --crate-name tokei src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort --cfg feature="all" --cfg feature="cbor" --cfg feature="default" --cfg feature="hex" --cfg feature="io" --cfg feature="json" --cfg feature="serde" --cfg feature="serde_cbor" --cfg feature="serde_derive" --cfg feature="serde_json" --cfg feature="serde_yaml" --cfg feature="toml" --cfg feature="toml-io" --cfg feature="yaml" -C metadata=efb1bd3f4d7a5843 -C extra-filename=-efb1bd3f4d7a5843 --out-dir /var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps -L dependency=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps --extern clap=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libclap-f3a9264198cbaed7.rlib --extern encoding_rs_io=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libencoding_rs_io-f6a53dafd054b317.rlib --extern env_logger=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libenv_logger-5f19482318962e0b.rlib --extern hex=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libhex-53172801cf21e299.rlib --extern ignore=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libignore-81e828585c28d6f7.rlib --extern log=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/liblog-d7f79fcf2fc59f6a.rlib --extern rayon=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/librayon-cc146f7e940e2a7b.rlib --extern serde=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libserde-9bb01d6292db5dfb.rlib --extern serde_cbor=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libserde_cbor-f33d14bec2f461a2.rlib --extern serde_derive=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libserde_derive-d8e6a72fb78940fe.dylib --extern serde_json=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libserde_json-9245940a74865f20.rlib --extern serde_yaml=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libserde_yaml-61119069ccbf654b.rlib --extern term_size=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libterm_size-7a4dd2960d247739.rlib --extern toml=/var/folders/xd/5x4c4j8s3zs9tvm3t7fjpx2r0000gn/T/cargo-install7hUTLK/release/deps/libtoml-bd4bff42e894724f.rlib --cap-lints allow` (exit code: 101)

See also https://circleci.com/gh/conda-forge/tokei-feedstock/4?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link 
and https://github.com/conda-forge/tokei-feedstock/pull/2/files

**Comment by Aaronepower** [comment]
This should now be fixed in `8.0.1`.

**Comment by dbast** [comment]
Thanks. Tokei 8.0.1 + "features all" is no available via conda:
- Platforms ![platforms](https://img.shields.io/conda/pn/conda-forge/tokei.svg)
- https://anaconda.org/conda-forge/tokei
- `conda install -c conda-forge tokei`

**Comment by Aaronepower** [comment]
@dbast Thank you, I've now included it in the README.

**Comment by dbast** [comment]
Cool! Thanks
