### ISSUE TITLE
tokei is slow

### ISSUE THREAD

**Issue by vlisivka** [Aaronepower/tokei#254]
Consider to use platter-walk and reapfrog crates. Also, some indication of progress with indicatif or spiners crates will be nice too.

**Comment by Aaronepower** [comment]
Thank you for your issue! This is not the place for filesystem improvements as tokei uses [`ignore`](https://github.com/BurntSushi/ripgrep/blob/master/ignore) to traverse the filesystem. Also tokei is typically under a half second under a hot cache so adding a progress indicator wouldn't really add much.
