### ISSUE TITLE
about the Chinese readme.md 😊

### ISSUE THREAD

**Issue by chinanf-boy** [Aaronepower/tokei#255]
### repo 
https://github.com/chinanf-boy/tokei-zh

**Comment by Aaronepower** [comment]
@chinanf-boy Thank you for your issue and for translating the repository! There's only a small issue in Languages section you're missing a code fence around the languages so that they are each on their own line. <https://github.com/chinanf-boy/tokei-zh#支持的语言>. I've included it in the README.

**Comment by chinanf-boy** [comment]
Sorry about that, I fix
