### ISSUE TITLE
Consider supporting "Hits of Code" (HOC) as an additional metric

### ISSUE THREAD

**Issue by golddranks** [Aaronepower/tokei#278]
An explanation of HOC, "Hits of Code": https://www.yegor256.com/2014/11/14/hits-of-code.html

While hits of code can defined only over repositories, not historyless directories, it provides a monotonically increasing metric (the amount of "code churn") and thus can show valuable things about the codebase changes that LOC misses.

**Comment by Aaronepower** [comment]
Thank you for your issue! I am interested in exploring more git aware tools with language detection (Such as [hera](https://github.com/Aaronepower/hera)), however I don't think this would be appropriate for inclusion in tokei itself as I don't see of an intuitive way to display multiple different kinds of statistics in a CLI. I could see a tool that uses tokei and incorporates other statistics like this. I'll keep this in mind for future projects, thank you!
