### ISSUE TITLE
The library API has problems.

### ISSUE THREAD

**Issue by dpc** [Aaronepower/tokei#288]
So, I want to use `tokei` in `crev` (https://github.com/dpc/crev/issues/156). I look at it - it comes with a library. Awesome. I look at https://docs.rs/tokei/8.0.1/tokei/ . Example that does almost what I need! Awesome.

Hmm.. but it is counting for the current directory... and I need a custom one ... Hmmm... How do I do that? Why are these paths `str`s, and not `Path`s? Confusing.

IMO, there should be an explicit argument somewhere: `root_path: &Path` and users that need counting in current dir would just pass `PathBuf::from(".")` or something. 

Anyway, that just a tiny annoyance, and I am very happy that I get all these functionality, as a library. Big thank you!

**Comment by dpc** [comment]
So I'm guessing I have to do 


```
    let paths = &[format!("{}/**/*.rs", my_root_path.display()];
```

or something like this?

Note that `display` is lossy, and it won't work correctly for non-utf8 paths, which are valid Unix paths.

**Comment by dpc** [comment]
What's the point of `pub fn remove_empty(&self) -> BTreeMap<&LanguageType, &Language>`? I just want all the languages. If there was no lines of given language, I am happy with zero. Otherwise, I remove empty, just to have to do `ok_or_else` to introduce `0` if there were no lines of Rust code where I was looking for.

**Comment by dpc** [comment]
```
    let paths = &[format!("{}/**/*.rs", my_root_path.display()];
```

didn't work. I get 0s everywhere... Eh... Still looking ...

**Comment by dpc** [comment]
OK. `let path = format!("{}", path.display());` worked. I still think this API is very confusing...

**Comment by Aaronepower** [comment]
Thank you for your issue! I've now changed the API to accept `&[AsRef<Path>]`.
