### ISSUE TITLE
Add License File

### ISSUE THREAD

**Issue by PhnxRbrn** [Aaronepower/tokei#3]
Please add a License file so we know if it is GPLv3 or MIT or so on.

**Comment by PhnxRbrn** [comment]
@Aaronepower Have you given any thought into what opensource license you will give this project?

**Comment by Aaronepower** [comment]
Yes, I'll be adding MIT.

**Comment by PhnxRbrn** [comment]
@Aaronepower Thank you for the quick response.  I just needed to know as I am packaging this utility up for Fedora via COPR and I just need the license added to do that.  Out of curiosity, should I add the SPEC file to your project?

**Comment by Aaronepower** [comment]
SPEC file? COPR? FEDORA? Could you explain these things?

**Comment by PhnxRbrn** [comment]
@Aaronepower Fedora is a Linux operating system run by RedHat.  Copr is an easy-to-use automatic build system providing a package repository as its output for Fedora.  SPEC files are the files that tell an rpm based distribution(Fedora, RedHat enterprise Linux, centos) how to build the package and install it.

**Comment by PhnxRbrn** [comment]
@Aaronepower Basically the reason for doing this is so that when you release a new version, I take the tar.gz and build it for Fedora.  I take that build add it to COPR and anyone who has the repository added to their system they will get an update through the package manager.

**Comment by Aaronepower** [comment]
Okay, sounds good to me! Make sure you use [version 1.1.1](https://github.com/Aaronepower/tokei/releases/tag/1.1.1) that I just released for your initial upload. Can you also comment back on this issue with instructions of how to install for people who use Fedora?
