### ISSUE TITLE
Defining a language with multiple comment-start and comment-end characters

### ISSUE THREAD

**Issue by cmr** [Aaronepower/tokei#30]
Isabelle theories want something like this

    Language::new("--", "{*,(*,‹,\\<open>", "*},*),›,\\<close>"),

Where all of those comment styles are used pretty ubiquitously.

**Comment by Aaronepower** [comment]
I'll probably change the multi-line comments from comma separated `&str`, to `Vec`'s, and the multi-line's will be in tuple pairings, so that comments aren't ended accidentally by a different closing comment.

**Comment by Aaronepower** [comment]
Fixed in 2.1.0
