### ISSUE TITLE
README.md animation no longer displaying

### ISSUE THREAD

**Issue by leijurv** [Aaronepower/tokei#302]
<img width="925" alt="screen shot 2019-02-11 at 10 27 25 pm" src="https://user-images.githubusercontent.com/3837873/52616127-47e39480-2e4c-11e9-81d3-9f0024854084.png">
<img width="915" alt="screen shot 2019-02-11 at 10 27 32 pm" src="https://user-images.githubusercontent.com/3837873/52616130-4914c180-2e4c-11e9-9866-f05ed115a631.png">

**Comment by Aaronepower** [comment]
Thank you for this issue! Closing this as a duplicate of #290
