### ISSUE TITLE
[Feature Request] Comment word count?

### ISSUE THREAD

**Issue by ZanderBrown** [Aaronepower/tokei#304]
How about (probably behind a flag) providing a word count in comments?

It's very interesting to know what you code:comment ratio looks like but sometimes it's would be nice to know how much you have actually written in those comments

**Comment by Aaronepower** [comment]
@ZanderBrown Thank you for your issue! This is definitely an interesting idea, however I think it is out of scope of tokei to provide that information. It would require a pretty big change to how tokei parses the files. 

If someone did want this tool I would suggest using tokei's `language.json` for easily going through each of the languages, and their comments.

**Comment by ZanderBrown** [comment]
Fair enough, another thing for the ideas board then :-)
