### ISSUE TITLE
Nested comments not handled

### ISSUE THREAD

**Issue by cmr** [Aaronepower/tokei#31]
Example `foo.rs`:

```rust
Foo 
/*

       Bar

       /*
    
       Baz

       */

    asdf
    'asdf
    asdf
    asdf
    asdf
    asdf
    asdf
    asdf
    asd
    fasdf
    asd
    f
    */
```

```
$ tokei foo.rs
-------------------------------------------------------------------------------
 Language            Files        Total       Blanks     Comments         Code
-------------------------------------------------------------------------------
 Rust                    1           24            5            5           14
-------------------------------------------------------------------------------
 Total                   1           24            5            5           14
-------------------------------------------------------------------------------
```

It counts the comment lines after the nested `*/` as code.

**Comment by Aaronepower** [comment]
I understand that languages support this, but I don't see how they are useful, I've never seen them used in practice, and there are a lot of languages that don't support nested, and so every language would now be required to specify whether they do or not, and that is a lot of research time(It was was hard to figure out certain languages comment syntax).

That being said if there is a strong reason to actually make this distinction. I will consider it.

**Comment by cmr** [comment]
The most frequent use of nested comments in languages that have it is to comment out large swathes of code. If that code itself contains a comment, which is likely, non-code is now reported as code, which is unfortunate for deriving metrics about a codebase from line counts.

**Comment by cmr** [comment]
I'm happy to do the research for nested-comment support. It's relatively uncommon AIUI, I imagine a new constructor for `Language` would be most appropriate.

**Comment by Aaronepower** [comment]
@cmr If you are attempting to derive metrics about a codebase why would you comment the code out, but not exclude the file? And just because you are willing to do the research now doesn't validate the effort of implementing, and maintaining this feature.

**Comment by cmr** [comment]
@Aaronepower because you don't own the codebase, you're just trying to run numbers on it, and don't know what untold horrors are in its source.

**Comment by Aaronepower** [comment]
There is now support for nested comments, all that is required is to add `.nested()` to a Language. Rust is the only one that uses it in 2.1.0.
