### ISSUE TITLE
JSON web API

### ISSUE THREAD

**Issue by rugk** [Aaronepower/tokei#310]
You support [generating badges](https://github.com/Aaronepower/tokei#badges), but a more general web API with JSON output or so would be nice.

The use case is that this can then be used in [shields](https://github.com/badges/shields/), which also has different badge styles etc. See issue https://github.com/badges/shields/issues/2731.

**Comment by conao3** [comment]
I found tokei.rs server code on https://github.com/Aaronepower/tokei_rs.

I think this issue should move to this repository.
Also, it may be better to specify the existence of this repository in the Readme.

**Comment by rugk** [comment]
moved to https://github.com/Aaronepower/tokei_rs/issues/8
