### ISSUE TITLE
RFE: Add loccount to your benchmarking derby

### ISSUE THREAD

**Issue by eric-s-raymond** [Aaronepower/tokei#315]
https://gitlab.com/esr/loccount

It's the result of translating sloccount to Go, then refactoring and generalizing until it has a fully general parser a la tokei (which I knew nothing of until yesterday). 138 languages.  I think you'd probably rate its accuracy as 'high'.

One unusual feature loccount has is that, for a large subset of its languages, it can do LLOC as well as SLOC.

The parallelization strategy is to scale the number of worker threads for files to the number of processors on the host machine.  Now that I know tokei and loc and scc exist, I'd be interested to see how loccount stacks up in performance.

**Comment by Aaronepower** [comment]
Sorry, I'm not interested in including your program in the document.

**Comment by eric-s-raymond** [comment]
Aaron Power <notifications@github.com>:
> Sorry, I'm not interested in including your program in the document.

I'm curious as to your reasoning.  How would it need to be different for you to
consider it eligible?
-- 
		<a href="http://www.catb.org/~esr/">Eric S. Raymond</a>

My work is funded by the Internet Civil Engineering Institute: https://icei.org
Please visit their site and donate: the civilization you save might be your own.

**Comment by Aaronepower** [comment]
There's nothing that would make it eligible. I'm not interested in including your work.

**Comment by eric-s-raymond** [comment]
Aaron Power <notifications@github.com>:
> There's nothing that would make it eligible. I'm not interested in including your work.

Your choice, but I do wonder why.
-- 
		<a href="http://www.catb.org/~esr/">Eric S. Raymond</a>

My work is funded by the Internet Civil Engineering Institute: https://icei.org
Please visit their site and donate: the civilization you save might be your own.
