### ISSUE TITLE
Tokei not finding files

### ISSUE THREAD

**Issue by infogulch** [Aaronepower/tokei#317]
Hi!

I'm working with a large repo, and when I run `tokei` in the project root it finds a tiny fraction of them the files.

```
repo> tokei          #   total 1013 files
repo/subdir1> tokei  #   total = 14112
repo/subdir2> tokei  #   total = 1136
[many other subdirs]
```

I'm running `tokei 9.0.0 compiled without serialization formats` on Windows 10.  I've tried in cmd, powershell, and git bash with the same results.

**Comment by infogulch** [comment]
I think it might be related to long paths since there are many very deeply nested files.

**Comment by Aaronepower** [comment]
@infogulch Tokei will ignore directories and files specified in `.gitignore` and `.ignore` files. If you want to count that whole directory on master there are the `--no-ignore`, `--no-ignore-parent`, and `--no-ignore-vcs` flags that can disable this behaviour.
