### ISSUE TITLE
prinit help when input nothing?

### ISSUE THREAD

**Issue by Roger-luo** [Aaronepower/tokei#318]
Currently, this search the root directory:

```
tokei
```

**Comment by Aaronepower** [comment]
@Roger-luo Thank you for your issue! I don't think this change would be very intuitive as `tokei` now currently behaves like other directory reading tools like `ls`, and this has been the default behaviour for a few years so there would be a heavy cost in having everyone now changing how they use the tool. For those reasons I'm going to close this issue, but feel free to reply if you have more on why you think the default behaviour should be changed.
