### ISSUE TITLE
Total rust lines of code

### ISSUE THREAD

**Issue by petevine** [Aaronepower/tokei#33]
If a `Cargo.lock` exists in a rust project, it should be possible to also include the dependencies from the local `.cargo` directory in offline mode. Probably via a `--deps` switch or similar.

Not sure about online mode or other languages. Have you considered this functionality?

**Comment by Aaronepower** [comment]
This sounds too specific to Rust, and to generalise it out to the rest of the languages would be an enormous task. Instead what I'm thinking is that along with what is discussed in #27 in regards to having Tokei output different formats, Tokei could also take in some input, so you can build on top of previous searches.

**Comment by Aaronepower** [comment]
With 2.1.0 you can now pass in previous results, so you can now have it so it counts the `.cargo` directory, and then pass in the result to the count on your project.

**Comment by petevine** [comment]
Thanks @Aaronepower !, I'll try it out promptly to see what it all means :)

**Comment by petevine** [comment]
Ok, you need to start from scratch but it gets the job done. 

```shell
$ rm -rf  ~/.cargo
$ cd myproject && cargo build
$ tokei -o json ~/.cargo | tokei -i stdin myproject/
````

Cool!

**Comment by Aaronepower** [comment]
@petevine you can also store the result of the previous, so you only need to enter a single command.
```
$ tokei -i stats.json .
```

**Comment by petevine** [comment]
I know but the issue was about counting dependencies of an arbitrary project, otherwise you'd have to keep separate saves depending on the `.cargo` contents.

**Comment by petevine** [comment]
What about a feature that would enable feeding `tokei` some coverage data to exclude dead library code? Presently we can count everything that gets compiled but not linked in:

$ tokei  -s code /tmp/.cargo/**/*.rs, tokei
````
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Rust                  520       273491       205924        53064        14503
 YAML                    2           62           58            3            1
 TOML                    1           58           36           17            5
 Autoconf                1            9            7            1            1
-------------------------------------------------------------------------------
 Total                 524       273620       206025        53085        14510
-------------------------------------------------------------------------------
````

**Comment by Aaronepower** [comment]
That's very Rust specific, where in other interpreted languages everything included is in the application. If you want something like that, I'd recommend writing an application that figures out what is complied in, and uses the `tokei` library for the code counting.

**Comment by petevine** [comment]
Right, in the above command `examples` and `tests` must have been included too. Provided everyone sticks to the naming convention, `tokei  /tmp/.cargo/**/lib.rs, ../tokei/` would have been closer to the truth:

````
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Autoconf                1            9            7            1            1
 Rust                   50        19849        12240         5785         1824
 TOML                    1           58           36           17            5
 YAML                    2           62           58            3            1
-------------------------------------------------------------------------------
 Total                  54        19978        12341         5806         1831
-------------------------------------------------------------------------------
````
