### ISSUE TITLE
Add Scala Language

### ISSUE THREAD

**Issue by WeAthFoLD** [Aaronepower/tokei#36]
* Name of the language: Scala
* File extensions: `.sc`, `.scala`
* Comment syntax: C syntax. Multi-line comments can be nested. From the [spec](http://www.scala-lang.org/files/archive/spec/2.11/13-syntax-summary.html):
```
comment ::=  
  ‘/*’ “any sequence of characters; nested comments are allowed” ‘*/’  |  
  ‘//’ “any sequence of characters up to end of line”
```

**Comment by Aaronepower** [comment]
Tokei, already has Scala in the latest version! It doesn't however have the `.sc` extension. I'll add that, and close this when the latest version is released.(_sometime this weekend or next week_)

**Comment by WeAthFoLD** [comment]
I am using tokei 2.0.0, but didn't see Scala file support using `tokei -l`, and it didn't count scala files either. I've seen it being added in the changelog though :3

Command line:
```
D:\> tokei -V
Tokei 2.0.0

D:\> tokei -l
ActionScript
Assembly
BASH
Batch
C
C Header
Clojure
CoffeeScript
ColdFusion
ColdFusion CFScript
Coq
C++
C++ Header
C#
C Shell
CSS
D
Dart
Device Tree
Erlang
FORTRAN Legacy
FORTRAN Modern
Go
Haskell
HTML
Idris
JAI
Java
JavaScript
Julia
JSON
JSX
Kotlin
LESS
LD Script
LISP
Lua
Makefile
Markdown
Mustache
Nim
Objective C
Objective C++
OCaml
Oz
Pascal
Perl
Polly
PHP
Protocol Buffers
Prolog
Python
QCL
R
Ruby
Ruby HTML
Rust
Sass
Standard ML
SQL
Swift
TeX
Plain Text
TOML
TypeScript
Vim Script
Unreal Script
Wolfram
XML
YAML
Zsh
```

**Comment by Aaronepower** [comment]
Ah, it wasn't added it to the BTreeMap. That'll be fixed in Tokei 2.1

**Comment by WeAthFoLD** [comment]
:+1:

**Comment by Aaronepower** [comment]
2.1.0 has been released
