### ISSUE TITLE
Tokei autoconf file mistaken as Rust code

### ISSUE THREAD

**Issue by Dean4Devil** [Aaronepower/tokei#45]
Tokei counts files with the ending `.in` as Rust code.

Tokei version `Tokei 2.1.1` (Installed via `cargo install` on stable rustc/cargo)

## Steps to reproduce:

 - `echo "a\n" > code.in`
 - `tokei code.in`

## Actual Results: 

code.in is counted as Rust code

## Expected Results:

code.in should be seen as autoconf input file.

**Comment by Aaronepower** [comment]
Fixed by 3.0.0
