### ISSUE TITLE
Use build.rs that does not break on Syntex updates

### ISSUE THREAD

**Issue by dtolnay** [Aaronepower/tokei#48]
https://github.com/Aaronepower/tokei/blob/f56efb6f22683a883a6c4da3d34705a180cc1077/src/lib/build.rs#L13-L16

See [this forum thread](https://users.rust-lang.org/t/here-is-how-to-avoid-being-broken-by-syntex-updates/6189?u=dtolnay) for the better version.

**Comment by Aaronepower** [comment]
Fixed
