### ISSUE TITLE
Inaccurate counts

### ISSUE THREAD

**Issue by jminer** [Aaronepower/tokei#51]
Today I thought I'd test Tokei before running it on my code, and I found some cases that it doesn't handle correctly. I'll include them in one issue because I assume they will be fixed by the same change, but I can split them into multiple issues if you'd like.

There are 8 lines of Rust code here, but Tokei reports 3:
~~~~~
fn main() {
    let start = "/*";
    loop {
        if x.len() >= 2 && x[0] == '*' && x[1] == '/' { // found the */
          break;
        }
    }
}
~~~~~

There are 6 lines of code here, but Tokei reports 5:
~~~~~
fn foo() {
    let no_comment = "
    // another test
    ";
    func();
}
~~~~~

There are 9 lines of code here, but Tokei panics:
~~~~~
fn foo() {
    let this_ends = "a \"test/*.";
    call1();
    call2();
    let this_does_not = /* a /* nested */ comment " */
                        "*/another /*test
    call3();
    */";
}
~~~~~

There are 10 lines of code here, but Tokei reports 7:
~~~~~
fn foobar() {
    let does_not_start = // "
        "until here,
        test/*
        test"; // a quote: "
    let also_doesnt_start = /* " */
        "until here,
        test,*/
        test"; // another quote: "
}
~~~~~

There are 5 lines of code here, but Tokei reports 2:
~~~~~
fn foo() {
    let a = 4; // /*
    let b = 5;
    let c = 6; // */
}
~~~~~

There are 5 lines of D code here, but Tokei reports 2:
~~~~~
void main() {
    auto x = 5; /+ a /+ nested +/ comment /* +/
    writefln("hello");
    auto y = 4; // */
}
~~~~~

I typed these out without trying to compile them, so sorry if I made a mistake.

I have written real world code where this kind of implementation would miscount a lot of code, so that's why I check out LOC counters before using them.

**Comment by Aaronepower** [comment]
@jminer Do you know of other CLOC(_not SLOC_) tools that handles these? I'd be interested to see their approach.

**Comment by jminer** [comment]
What is the difference between CLOC and SLOC tools? I tried searching Google but can't find those terms used.

I got some time to try [Ohcount](https://github.com/blackducksoftware/ohcount). It seems to get all of them correct, except that it doesn't seem to count newlines in strings and doesn't support Rust's nested comments. I thought I had tested [cloc](https://github.com/AlDanial/cloc) in the past and it handled these correctly, but it does not. I don't think I will use it anymore.

Thanks for fixing this! I'll probably always use Tokei when I want to count code.

**Comment by Aaronepower** [comment]
@jminer CLOC counters have their limits due to being generic. You could write lexically invalid code, that a CLOC tool will miscount. SLOC's count using an actual parser of the language. SLOC's tend to be of only one language, and can count much more in-depth things like number of statements. This is probably the limit of tokei's general accuracy. 

```
// one line of code, two statements.
let x = 1; let y = 2;
```
