### ISSUE TITLE
Update existing languages with their String litreals.

### ISSUE THREAD

**Issue by Aaronepower** [Aaronepower/tokei#52]
Now with the inclusion handling comments while in quotes, and out of them. All existing languages need to be updated with their string type as currently the default is `(", ")` which obviously doesn't apply to all languages. All that is needed to go to `src/lib/language/languages.rs` and use the `set_quotes()` method.

- [ ] ActionScript
- [ ] Ada
- [x] Assembly
- [ ] Autoconf
- [x] BASH
- [x] Batch
- [x] C
- [x] C Header
- [x] Clojure
- [x] CoffeeScript
- [x] ColdFusion
- [x] ColdFusion CFScript
- [ ] Coq
- [x] C++
- [x] C++ Header
- [ ] C#
- [ ] C Shell
- [x] CSS
- [ ] D
- [x] Dart
- [ ] Device Tree
- [ ] Erlang
- [ ] Forth
- [ ] FORTRAN Legacy
- [ ] FORTRAN Modern
- [ ] Go
- [ ] Handlebars
- [x] Haskell
- [x] HTML
- [x] Idris
- [ ] Isabelle
- [x] JAI
- [x] Java
- [x] JavaScript
- [x] Julia
- [x] JSON
- [ ] JSX
- [x] Kotlin
- [ ] LESS
- [ ] LD Script
- [ ] LISP
- [ ] Lua
- [ ] Makefile
- [x] Markdown
- [ ] Mustache
- [ ] Nim
- [ ] Objective C
- [ ] Objective C++
- [ ] OCaml
- [ ] Oz
- [ ] Pascal
- [ ] Perl
- [ ] Polly
- [x] PHP
- [ ] Protocol Buffers
- [ ] Prolog
- [ ] Python
- [ ] QCL
- [ ] R
- [ ] Ruby
- [ ] Ruby HTML
- [x] Rust
- [ ] Sass
- [ ] Scala
- [ ] Standard ML
- [ ] SQL
- [ ] Swift
- [ ] TeX
- [x] Plain Text
- [ ] TOML
- [ ] TypeScript
- [ ] Vim Script
- [ ] Unreal Script
- [ ] Wolfram
- [ ] XML
- [ ] YAML
- [x] Zsh

**Comment by abhiQmar** [comment]
Can you please give an example? I don't quite get it.

```
CoffeeScript => Language::new(vec!["#"], vec![("###", "###")])
                                     .set_quotes(vec![("\"", "\""), ("'", "'")])
```
In this constructor we have single line and multiline comment styles being passed. What does the set_quotes function do?

**Comment by Aaronepower** [comment]
@abhiQmar So by default all languages have `[(", ")]`. In that example all JavaScript and it's superset languages(_CoffeeScript, TypeScript_) also have `''` to represent String literals. So `set_quotes` just overrides the default.

**Comment by mwilli20** [comment]
Is this still an issue. I don't see anywhere in the code saying which strings aren't done or not. If it isn't done am I too assume the original list is accurate in what needs to be implemented.

**Comment by Aaronepower** [comment]
@mwilli20 The list in this issue is the canonical list. You are correct in assuming that when the list says it isn't done, it isn't done. Some probably done through the fact that the default `(", ")`, applies to them. And just need to be verified.

**Comment by mwilli20** [comment]
Is there anywhere you know of with a complete and accurate list of this information. If so this seems like an easy issue I could tackle.

On a somewhat related note I see set_quotes is for strings, and new is comments in general, nested comments for that type as well but new_c, new_single, new_hash and etc. what are all these defaults?

I ask only because Haskell says new single but it has two types of comments
-- InlineComment 	{- BlockComment -} , I could go through and double check comments as well.
https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(syntax)#Comments

**Comment by Aaronepower** [comment]
@mwilli20 `new_*` is always required. `new` requires all the parameters, the rest are just conveivence constructors. So for example if a language's syntax is exactly like C then I just use `new_c`. `set_quotes` just overrides the defaults. You can see them all in `lib/language/language.rs`

**Comment by Aaronepower** [comment]
@mwilli20 There only way is to spend time searching for a language spec, or reference or similar. For any language you submit also provide it for verification. Feel free to double check my comments if you'd like.

**Comment by Aaronepower** [comment]
@mwilli20 Can you confirm that you've covered all the open languages on the list?

**Comment by mwilli20** [comment]
@Aaronepower Yes all languages on the list have been covered. 

In pull reqeust #61, for any language that  uses " " only I didn't edit it due to the constructors, except forth which used new, which had no default quote setting.

**Comment by Aaronepower** [comment]
@mwilli20 Good enough for me.
