### ISSUE TITLE
Notify user about errors when processing files

### ISSUE THREAD

**Issue by crumblingstatue** [Aaronepower/tokei#54]
Right now, tokei just silently ignores errors (like invalid encoding) when processing source files.
This leads to the user seeing incorrect results in these cases, without knowing that they are incorrect because errors happened when processing the files.

**Comment by Aaronepower** [comment]
@crumblingstatue I definitely agree. I have been doing this anyway on my local versions to catch file extensions it doesn't count. What I've been thinking of is a verbose counter like clap does in it's examples.

```
-v print file IO errors
-vv plus print non counted file paths.
```

**Comment by crumblingstatue** [comment]
So I/O errors are printed only when the `-v` flag is passed?
Aren't I/O errors serious and exceptional enough that tokei should warn about them by default?
What if an I/O error happens, and the user has no idea, while tokei silently gives incorrect results?
The user wouldn't know that the results were incorrect, unless he compared the results to another tool's (like cloc) output. And even if he realized they are incorrect, he could think that it's just an error in the way tokei counts the lines, and not an I/O error (unless he knows to rerun with -v in case results are incorrect).

**Comment by Aaronepower** [comment]
@crumblingstatue You're right. I've changed it now.
