### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by Stebalien** [Aaronepower/tokei#80]
Please tag the last 3 releases (for packagers).

**Comment by Aaronepower** [comment]
Does git not push tags up? I definetly tagged the first release.

**Comment by Stebalien** [comment]
You have to use `git push --tags` or set `git config push.followTags true` to automatically push them.

**Comment by Aaronepower** [comment]
Alright I've tag the two releases, but only the latest should be used since 4.50 and 4.5.1 don't work. What packagers are packaging tokei?

**Comment by Stebalien** [comment]
There's a PKGBUILD in the AUR (Arch Linux).
