### ISSUE TITLE
Comments uncounted when based on FUNC_REGEX

### ISSUE THREAD

**Issue by tuncer** [Aaronepower/tokei#89]
OCaml, Coq, etc. comments are for some reason not counted.

**Comment by Aaronepower** [comment]
Can you provide an example code base, or file that can be used to test against?

**Comment by tuncer** [comment]
If you run it on https://github.com/FStarLang/FStar/, it will find Coq and OCaml but list 0 lines of comments for those files. Same issue for any config based on FUNC_REGEX.

**Comment by Aaronepower** [comment]
@tuncer Can you check if you're still getting the problem with the new version? And if you are can you provide so some code to test in `src/test/data`? Thanks you.

**Comment by tuncer** [comment]
It counts comments now, do you still need/want test files? What was the bug or how did you fix it?

**Comment by Aaronepower** [comment]
@tuncer I don't need them, but feel free to add some to `tests/data` include a comment on the first one like the other ones that contains how much lines/code/etc it should have, and tokei will automatically add that to the test suite.

**Comment by Aaronepower** [comment]
@tuncer I think the REGEX just wasn't being escaped properly.
