### ISSUE TITLE
Language flag does not work

### ISSUE THREAD

**Issue by PhnxRbrn** [Aaronepower/tokei#9]
If you use -l or --languages it returns the error the following required arguments were not supplied: '<input>...'. But you should not have to provide input when seeing the list of supported languages

**Comment by Aaronepower** [comment]
Yes, I've noticed that too. I'm not sure what to do with this one. I'll have a look into clap, and see if clap has an option to ignore required arguments. If not I'll make an issue to clap to see if I can get that added.

**Comment by Aaronepower** [comment]
Once I find out the `negate_subcommands_arg` equivalent  in YAML, this will be fixed

**Comment by Aaronepower** [comment]
Fixed by 99b420783f24e3d564883dad7b6b35124bde987a
