### ISSUE TITLE
統計？　時計？

### ISSUE THREAD

**Issue by fulmicoton** [Aaronepower/tokei#97]
The kanjis in the readme mean "a clock / a watch".
Did you mean statistics? If so I believe this is written 統計

**Comment by Aaronepower** [comment]
No I didn't. Tokei/時計 means a clock. Which is a play on [CLOC](https://github.com/AlDanial/cloc) which was the original inspiration for this project.

**Comment by fulmicoton** [comment]
Oh I see :) ! Cool
